#!/bin/bash
build=~/downloads/InSaNiTy
kernel="InSaNiTy"
version="1.3"
rom="aosp"
variant="falcon"
ramdisk=ramdisk
toolchain=~/kernel/kernel_motorola_msm8226/toolchain/bin/
toolchain2="arm-eabi-"
config="msm8226_mmi_defconfig"
kerneltype="zImage-dtb"
jobcount="-j$(grep -c ^processor /proc/cpuinfo)"
ps=2048
base=0x00000000
ramdisk_offset=0x01000000
tags_offset=0x00000100
cmdline="console=ttyHSL0,115200,n8 androidboot.console=ttyHSL0 androidboot.hardware=qcom user_debug=31 msm_rtb.filter=0x37 vmalloc=400M utags.blkdev=/dev/block/platform/msm_sdcc.1/by-name/utags androidboot.write_protect=0 zcache androidboot.selinux=permissive"

if [ "$1" = "local" ]; then
	build=~/downloads/InSaNiTy
	toolchain=~/kernel/kernel_motorola_msm8226/toolchain/bin/
fi

rm -rf out
mkdir out
mkdir out/tmp
echo "Checking for build..."
if [ -f ozip/boot.img ]; then
	read -p "Previous build found, clean working directory..(y/n)? : " cchoice
	case "$cchoice" in
		y|Y )
			export ARCH=arm
			export CROSS_COMPILE=$toolchain/"$toolchain2"
			echo "  CLEAN   ozip"
			rm -rf ozip/boot.img
			rm -rf arch/arm/boot/"$kerneltype"
			mkdir -p ozip/system/lib/modules
			make clean && make mrproper
			echo "Working directory cleaned...";;
		n|N )
			exit 0;;
		* )
			echo "Invalid...";;
	esac
	read -p "Begin build now..(y/n)? : " dchoice
	case "$dchoice" in
		y|Y)
			make "$config"
			make "$jobcount"
			exit 0;;
		n|N )
			exit 0;;
		* )
			echo "Invalid...";;
	esac
fi
echo "Extracting files..."
if [ -f arch/arm/boot/"$kerneltype" ]; then
	cp arch/arm/boot/"$kerneltype" out
	rm -rf ozip/system
	mkdir -p ozip/system/lib/modules
	find . -name "*.ko" -exec cp {} ozip/system/lib/modules \;
	if [ -f ozip/system/lib/modules/radio-iris-transport.ko ]; then
		echo "Modules found!"
		echo "Doing $variant specific module changes!"
		if [ -f ozip/system/lib/modules/wlan.ko ]; then
			mkdir ozip/system/lib/modules/pronto
			mv ozip/system/lib/modules/wlan.ko ozip/system/lib/modules/pronto/pronto_wlan.ko
		else
			echo "wlan.ko not found!"
		fi
	else
		rm -rf ozip/system
	fi
else
	echo "Nothing has been made..."
	read -p "Clean working directory..(y/n)? : " achoice
	case "$achoice" in
		y|Y )
			export ARCH=arm
			export CROSS_COMPILE=$toolchain/"$toolchain2"
			if [ -f arch/arm/boot/"$kerneltype" ]; then
				echo "  CLEAN   ozip"
			fi
			rm -rf ozip/boot.img
			rm -rf arch/arm/boot/"$kerneltype"
			mkdir -p ozip/system/lib/modules
			make clean && make mrproper
			echo "Working directory cleaned...";;
		n|N )
			exit 0;;
		* )
			echo "Invalid...";;
	esac
	read -p "Begin build now..(y/n)? : " bchoice
	case "$bchoice" in
		y|Y)
			make "$config"
			make "$jobcount"
			exit 0;;
		n|N )
			exit 0;;
		* )
			echo "Invalid...";;
	esac
fi

echo "Making ramdisk..."
if [ -d $ramdisk ]; then
	mkbootfs $ramdisk | gzip > out/ramdisk.gz
else
	echo "No ramdisk found..."
	exit 0;
fi

echo "Making boot.img..."
if [ -f out/"$kerneltype" ]; then
	mkbootimg --kernel out/"$kerneltype" --ramdisk out/ramdisk.gz --cmdline "$cmdline" --base $base --pagesize $ps --ramdisk_offset $ramdisk_offset --tags_offset $tags_offset -o ozip/boot.img
else
	echo "No $kerneltype found..."
	exit 0;
fi

echo "Zipping..."
if [ -f arch/arm/boot/"$kerneltype" ]; then
	cd ozip
	zip -r ../"$kernel"-$version-"$rom"_"$variant".zip .
	mv ../"$kernel"-$version-"$rom"_"$variant".zip $build
	cd ..
	rm -rf out ramdisk.gz ozip/system
	echo "Done..."
	exit 0;
else
	echo "No $kerneltype found..."
	exit 0;
fi
# Export script by Cannondalev2000
